# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0fe8a78100c78bb83364c85b64ab17b2b9edb39183800eb96adb7bd723d764fb6795eda44788b411622a15d1799779e5835b6bf7c25a8e8267299f81f4a3b1e9

test:
  secret_key_base: c68c59140530b37db17438315495d80152eea00c816bcfc867ce5a9d13e1b2b6a178b048e546b898f855b74a0bb14975dc6ab8f93fb717e0118853eea02f43c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
